Feature/uc choosing
NIAEFEUP/tts-revamp-fe pull request #21
Opened 2021-12-13 20:43 UTC by kiko-g

2021-12-15 19:10 UTC, TiagooGomess requested changes
Nice work. Just a suggestion: maybe we don't need the autocomplete for fields that are numbers, `Semestre` and `Ano Letivo`. There is an error in the console because of using numbers in the autocomplete:
![Screenshot from 2021-12-15 19-08-27](https://user-images.githubusercontent.com/50210213/146249690-39efff0c-4787-44a8-b578-29d114748aea.png)
Maybe we can have just a simple dropdown.

2022-01-06 23:17 UTC, TiagooGomess commented
Are we going to use a 2 space indentation?

2022-01-06 23:18 UTC, TiagooGomess requested changes

2022-01-06 23:18 UTC, TiagooGomess commented on .prettierrc
> +    "singleQuote": true
Just a suggestion: 
```suggestion
    "tabWidth": 4,
    "useTabs": false,
    "semi": true,
    "singleQuote": false
```

2022-01-07 09:48 UTC, TiagooGomess commented
Please update the changed files tab width to the new configuration (4 instead of 2).

2022-01-18 21:13 UTC, kiko-g commented
![image](https://user-images.githubusercontent.com/40745490/150019658-eee19193-15b9-4824-a7e2-216db56f4b9c.png)

If everyone can agree on this configuration this is ready to merge

2022-01-18 21:32 UTC, TiagooGomess approved these changes

2022-01-29 14:26 UTC, merged